# Exported from Render on 2025-01-29T00:30:35Z
services:
- type: web
  name: Sitecore
  runtime: node
  repo: https://github.com/yesman234/Sitecore
  plan: starter
  envVars:
  - fromGroup: NodeJS_mysql
  region: oregon
  buildCommand: npm install
  startCommand: npm start
version: "1"
