# Exported from Render on 2025-01-18T21:05:06Z
services:
- type: web
  name: Sitecore
  runtime: node
  repo: https://github.com/yesman234/Sitecore
  plan: starter
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
  autoDeploy: false
version: "1"
