services:
- type: web
  name: Sitecore_library
  runtime: node
  repo: https://github.com/yesman234/Sitecore.git
  plan: free
  region: oregon
  buildCommand: npm install
  startCommand: node server.js
version: "1"
databases:
  - name: sitecore_library # A PostgreSQL database named django-app-db running on a free instance
    plan: free