
version: "1"
# Exported from Render on 2025-01-29T00:30:35Z
services:
- type: web
  name: Sitecore
  runtime: Docker
  repo: https://github.com/yesman234/Sitecore
  plan: starter
  envVars:
  - fromGroup: NodeJS_mysql
  region: oregon
  buildCommand: npm install
  startCommand: npm start
  envVarGroups:
- name: mysql
  envVars:
  - key: MYSQL_DATABASE
    value: sitecore_library
  - key: MYSQL_USER
    value: data_analyst
  - key: password
    generateValue: true
  - key: password
    generateValue: true