
version: "1"
name: mysql
plan: standard
env: docker
autoDeploy: false
disk: mysql
mountPath: /var/lib/mysql
# Exported from Render on 2025-01-29T00:30:35Z
services:
- type: web
  name: Sitecore
  runtime: node
  repo: https://github.com/yesman234/Sitecore
  plan: starter
  envVars:
  - fromGroup: production
  region: oregon
  buildCommand: npm install
  startCommand: npm start